// Real-asset 817:3 render entry. Loads the genuine bundle generated by the
// Figma REST import (lumencast-figma .local-exports, symlinked under ./real/),
// rewrites its content-addressed `assets/<hash>.png` image refs to the
// HTTPS dev origin (so the runtime host-allow gate passes: https + allowlisted
// host), and renders it through the PRODUCTION BroadcastMode path into a fixed
// 1920×1080 stage for a Playwright screenshot.

import { createRoot } from "react-dom/client";
import { createElement, StrictMode } from "react";
import { createStore } from "../../../src/state/store";
import { BroadcastMode } from "../../../src/modes/broadcast";
import { LumencastRuntimeProvider } from "../../../src/overlay/runtime-context";
import { compileBundle } from "../../../../compiler/src/index";

const REAL_BASE = "/tests/e2e/zero-loss/real/";

async function main(): Promise<void> {
  const res = await fetch(REAL_BASE + "bundle.json?t=" + Date.now(), { cache: "no-store" });
  const bundle = (await res.json()) as {
    assets?: { allowedHosts?: string[]; [k: string]: unknown };
    defaults?: Record<string, unknown>;
    layout: unknown;
    [k: string]: unknown;
  };

  // Allowlist the dev host so the runtime gate admits the served assets.
  bundle.assets = { ...(bundle.assets ?? {}), allowedHosts: ["localhost"] };

  // Rewrite EVERY content-addressed `assets/<hash>.png` ref anywhere in the
  // bundle (defaults image refs AND layout mask.source.src / image fills) to an
  // absolute HTTPS URL on this origin, so the runtime host gate admits them.
  const rewrite = (s: string): string =>
    s.startsWith("assets/") ? `${location.origin}${REAL_BASE}${s}` : s;
  const walk = (node: unknown): void => {
    if (node === null || typeof node !== "object") return;
    if (Array.isArray(node)) {
      for (const v of node) walk(v);
      return;
    }
    const obj = node as Record<string, unknown>;
    for (const k of Object.keys(obj)) {
      const v = obj[k];
      if (typeof v === "string") obj[k] = rewrite(v);
      else walk(v);
    }
  };
  walk(bundle.layout);
  const defaults: Record<string, unknown> = { ...(bundle.defaults ?? {}) };
  walk(defaults);

  const compiled = compileBundle(bundle as never, {
    onWarn: (m: string) => console.warn("[real:compile]", m),
  });

  const store = createStore();
  store.reset(defaults);

  const target = document.getElementById("scene");
  if (!(target instanceof HTMLElement)) throw new Error("real harness: #scene missing");

  const root = createRoot(target);
  root.render(
    createElement(
      StrictMode,
      null,
      createElement(
        LumencastRuntimeProvider,
        {
          value: {
            mode: "broadcast",
            store,
            bundle: compiled,
            status: "live",
            sendInput: () => {},
          },
        },
        createElement(BroadcastMode),
      ),
    ),
  );

  requestAnimationFrame(() => {
    requestAnimationFrame(() => {
      (window as unknown as { __harnessReady: boolean }).__harnessReady = true;
    });
  });
}

void main();
